CREATE TABLE "T" ("A" NUMBER(4,0));

CREATE OR REPLACE EDITIONABLE TRIGGER "TR"
BEFORE INSERT
ON "T"
FOR EACH ROW
BEGIN
  IF :NEW.A IS NULL THEN
    :NEW.A := 1;
  END IF;
END;

CREATE OR REPLACE EDITIONABLE TRIGGER "TR2"
    BEFORE INSERT ON T
    FOR EACH ROW
    WHEN (NEW.A IS NULL)
BEGIN
    $IF DBMS_DB_VERSION.VER_LE_10 $THEN
        -- 10G
        SELECT S_CONCEPT_SAMPLE.NEXTVAL INTO :NEW.A FROM DUAL;
    $ELSE
        -- 11G
        :NEW.A := S_CONCEPT_SAMPLE.NEXTVAL;
    $END
END;